services:
  postgres:
    image: 'postgres:latest'
    container_name: db
    environment:
      - 'POSTGRES_DB=items'
      - 'POSTGRES_PASSWORD=secret'
      - 'POSTGRES_USER=myuser'
    ports:
      - '5432:5432'

  pgadmin:
    image: dpage/pgadmin4
    container_name: pgadmin4_container
    restart: unless-stopped
    ports:
      - '5016:80'
    user: "$UID:$GID"
    environment:
      - PGADMIN_DEFAULT_EMAIL=demo@demo.com
      - PGADMIN_DEFAULT_PASSWORD=password